sonar.projectKey=vincent-bartissol_dashboard
sonar.projectName=Paris Ouverte

sonar.sources=app,components,lib,i18n,proxy.ts,instrumentation.ts,instrumentation-client.ts,instrumentation.node.ts
sonar.exclusions=**/.next/**,**/node_modules/**,**/data/**,**/e2e/**,**/*.test.ts,**/*.test.tsx,**/lib/db/migrations/**,**/pnpm-lock.yaml

sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json
